document.write('<nav style="position: sticky;position: -webkit-sticky;top: 0;background-color:#333;display:block" class="top-bar" data-topbar>')
document.write('	<ul class="title-area">')
document.write('		<li id="homepage" class="name">')
document.write('		<a href="index.html"><img src="../images/icon.jpg" width="47px" style="margin-top: -5px; display: inline;"><h1 style="display: inline;color: white;">&nbspYu#39s website&nbsp</h1></a>')
document.write('    </li>')
document.write('    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>')
document.write('</ul>')
document.write('')
document.write('<section class="top-bar-section">')
document.write('	<ul class="left">')
document.write('		<li><a href="https://space.bilibili.com/1804589711" target="_blank">My bilibili homepage</a></li>')
document.write('		<li id="friends"><a href="friends.html">My friends</a></li>')
document.write('		<li><a href="https://vdse.bdstatic.com//192d9a98d782d9c74c96f09db9378d93.mp4" target="_blank">BAIPIAO my MC account</a></li>')
document.write('		<li><a href="mailto:henryyu1003@163.com" target="_blank">Contact me</a></li>')
document.write('	</ul>')
document.write('</section>')
document.write('</nav>')
document.write('<br><br>')
